### ISSUE TITLE
Treasury Dashboard

### ISSUE THREAD

**Issue by josephd8** [SetProtocol/index-coop-analytics#1]
We need to build out a full Treasury Dashboard. The Treasury Working Group is currently working on requirements documentation for all the analytics we need for them to properly manage and report on the treasury.

**Comment by josephd8** [comment]
Lots of work to do here - will need to be an iterative process. 

Going to start with the base view of all Treasury assets (both usd and units) over time and then build out view-by-view with the Treasury groups guidance.

**Comment by josephd8** [comment]
@jackiep00

**Comment by jackiep00** [comment]
hello!

**Comment by jackiep00** [comment]
Hey all, we discovered through our iteration process that the primary need for TWG was to be able to do transaction-level tagging and notation on top of live data - we have discovered that Dune is not the right tool for this and we are closing this workstream.

I will continue to be point person for TWG if additional requests pop up, but I am closing this issue for now since there is no outstanding work to be done.
